name: driver_passenger_app
description: "Driver and passenger ride app — GetX modular architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  avatar_glow: ^3.0.1
  flutter_screenutil: ^5.9.3
  geolocator: ^14.0.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist[wght].ttf
